# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Publish Docs Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # NOTE: Action to tag repo, publish documents only enabled for "onosproject"
  # CAUTION: Other actions depend on this name "tag-github"
  tag-github:
    uses: onosproject/.github/.github/workflows/tag-github.yml@main
    secrets: inherit

  update-version:
    needs: tag-github
    if: needs.tag-github.outputs.changed == 'true'
    uses: onosproject/.github/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      version: ${{ needs.tag-github.outputs.version }}

  publish:
    needs: tag-github
    if: github.repository_owner == 'onosproject'
    uses: onosproject/.github/.github/workflows/docs-publish.yml@main
    with:
      remote_host: static.opennetworking.org
      remote_path: /srv/sites/docs.sd-ran.org/
    secrets: inherit
